[project]
name = "dagster_project"
version = "0.1.0"
description = "A simple Dagster project"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.6",
    "dagster-webserver>=1.6",
    "pandas"
]

[tool.dagster]
module_name = "dags"
